spring:
  application:
    name: hotel-service

  datasource:
    url: jdbc:postgresql://localhost:5432/hoteldb
    username: hotelapp
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.hotelapp: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/hoteldb

server:
  port: 8080