spring:
  #profiles:
    #active: local

  application:
    name: hotel-service

  datasource:
    url: jdbc:postgresql://hotel-db:5432/hoteldb
    username: hotelapp
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
    path: /docs/hotels/v3/api-docs
  swagger-ui:
    enabled: false
    path: /docs/hotels/swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.hotelapp: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE