spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/hoteldb
    username: hotelapp
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
